
export const MusicData=[
    {
        id:"1",
        heading:"Focus",
        img1: "./asstes/1.jpeg",
        img2:"./asstes/2.jpeg",
        img3:"./asstes/3.jpeg",
        img4:"./asstes/4.jpeg",
        img5:"./asstes/5.jpeg",
        img6:"./asstes/6.jpeg",
        title1:"Peaceful Piano",
        subtitle1:"Relax and indulge with beautiful piano pieces",
        title2:"Deep Focus",
        subtitle2:"Keep calm and focus with ambient and post-rock...",
        title3:"Instrumental Study",
        subtitle3:"Focus with soft study music in the background.",
        title4:"Workday Lounge",
        subtitle4:"Lounge and chill out music for your workday.",
        title5:"Focus Flow",
        subtitle5:"Uptempo instrumental hip hop beats.",
        title6:"Beats to think to",
        subtitle6:"Focus with deep techno and tech house.",
    },
    {
        id:"2",
        heading:"Spotift Playlists",
        img1: "./asstes/Spotify Playlists/1.jpeg",
        img2:"./asstes/Spotify Playlists/2.jpeg",
        img3:"./asstes/Spotify Playlists/3.jpeg",
        img4:"./asstes/Spotify Playlists/4.jpeg",
        img5:"./asstes/Spotify Playlists/5.jpeg",
        img6:"./asstes/Spotify Playlists/6.jpeg",
        title1:"Today's Top Hits",
        subtitle1:"The Weekend is on top of the Hottest 50!",
        title2:"RapCaviar",
        subtitle2:"Music from Lil Uzi Vert,Drake and Maneybagg Yo.",
        title3:"All Out 2010s",
        subtitle3:"The biggest songs of the 2010s.",
        title4:"Rock Classics",
        subtitle4:"Rock legends & epic songs that continue to inspire...",
        title5:"Chill Hits",
        subtitle5:"Kick back to the best new and recent chill hits",
        title6:"Viva Latino",
        subtitle6:"Today's top Latin hits elevando nuestra musica...",
    },
    {
        id:"3",
        heading:"Sound of India",
        img1: "./asstes/Sound of India/1.jpeg",
        img2: "./asstes/Sound of India/2.jpeg",
        img3: "./asstes/Sound of India/3.jpeg",
        img4: "./asstes/Sound of India/4.jpeg",
        img5: "./asstes/Sound of India/5.jpeg",
        img6: "./asstes/Sound of India/6.jpeg",
        title1:"The Sound of Mumb..",
        subtitle1:"The songs that define unite and distinguish...",
        title2:"The Sound of Kolkat...",
        subtitle2:"The songs that define unite and distinguish...",
        title3:"The Sound of Delhi IN.",
        subtitle3:"The songs that define unite and distinguish...",
        title4:"The Sound of Bengal...",
        subtitle4:"The songs that define unite and distinguish...",
        title5:"The Sound of Chenn..",
        subtitle5:"The songs that define unite and distinguish...",
        title6:"The Sound of Hyder..",
        subtitle6:"The songs that define unite and distinguish...",
    },
   
]

// export const MusicData1=[
//     {
//         id:"1",
//         heading:["Focus","Spotift Playlists","Sound of India"],
//         imgs:[ "./asstes/1.jpeg", "./asstes/2.jpeg", "./asstes/3.jpeg", "./asstes/4.jpeg", "./asstes/5.jpeg", "./asstes/6.jpeg",],
//         imgs1:["./asstes/Spotify Playlists/1.jpeg","./asstes/Spotify Playlists/2.jpeg","./asstes/Spotify Playlists/3.jpeg","./asstes/Spotify Playlists/4.jpeg","./asstes/Spotify Playlists/5.jpeg","./asstes/Spotify Playlists/6.jpeg",],
//         title:["Peaceful Piano","Deep Focus","Instrumental Study","Workday Lounge","Focus Flow","Beats to think to"],
//         subtitle:["Relax and indulge with beautiful piano pieces","Keep calm and focus with ambient and post-rock...","Focus with soft study music in the background.",
//                   "Lounge and chill out music for your workday.","Uptempo instrumental hip hop beats.","Focus with deep techno and tech house.",
//                 ]
//             },
//         // img1: "./asstes/1.jpeg",
//         // img2:"./asstes/2.jpeg",
//         // img3:"./asstes/3.jpeg",
//         // img4:"./asstes/4.jpeg",
//         // img5:"./asstes/5.jpeg",
//         // img6:"./asstes/6.jpeg",
//         // title1:"Peaceful Piano",
//         // subtitle1:"Relax and indulge with beautiful piano pieces",
//         // title2:"Deep Focus",
//         // subtitle2:"Keep calm and focus with ambient and post-rock...",
//         // title3:"Instrumental Study",
//         // subtitle3:"Focus with soft study music in the background.",
//         // title4:"Workday Lounge",
//         // subtitle4:"Lounge and chill out music for your workday.",
//         // title5:"Focus Flow",
//         // subtitle5:"Uptempo instrumental hip hop beats.",
//         // title6:"Beats to think to",
//         // subtitle6:"Focus with deep techno and tech house.",


//     // {
//     //     id:"2",
//     //     heading:"Spotift Playlists",
//     //     img1: "./asstes/Spotify Playlists/1.jpeg",
//     //     img2:"./asstes/Spotify Playlists/2.jpeg",
//     //     img3:"./asstes/Spotify Playlists/3.jpeg",
//     //     img4:"./asstes/Spotify Playlists/4.jpeg",
//     //     img5:"./asstes/Spotify Playlists/5.jpeg",
//     //     img6:"./asstes/Spotify Playlists/6.jpeg",
//     //     title1:"Today's Top Hits",
//     //     subtitle1:"The Weekend is on top of the Hottest 50!",
//     //     title2:"RapCaviar",
//     //     subtitle2:"Music from Lil Uzi Vert,Drake and Maneybagg Yo.",
//     //     title3:"All Out 2010s",
//     //     subtitle3:"The biggest songs of the 2010s.",
//     //     title4:"Rock Classics",
//     //     subtitle4:"Rock legends & epic songs that continue to inspire...",
//     //     title5:"Chill Hits",
//     //     subtitle5:"Kick back to the best new and recent chill hits",
//     //     title6:"Viva Latino",
//     //     subtitle6:"Today's top Latin hits elevando nuestra musica...",
//     // },
//     // {
//     //     id:"3",
//     //     heading:"Sound of India",
//     //     img1: "./asstes/Sound of India/1.jpeg",
//     //     img2: "./asstes/Sound of India/2.jpeg",
//     //     img3: "./asstes/Sound of India/3.jpeg",
//     //     img4: "./asstes/Sound of India/4.jpeg",
//     //     img5: "./asstes/Sound of India/5.jpeg",
//     //     img6: "./asstes/Sound of India/6.jpeg",
//     //     title1:"The Sound of Mumb..",
//     //     subtitle1:"The songs that define unite and distinguish...",
//     //     title2:"The Sound of Kolkat...",
//     //     subtitle2:"The songs that define unite and distinguish...",
//     //     title3:"The Sound of Delhi IN.",
//     //     subtitle3:"The songs that define unite and distinguish...",
//     //     title4:"The Sound of Bengal...",
//     //     subtitle4:"The songs that define unite and distinguish...",
//     //     title5:"The Sound of Chenn..",
//     //     subtitle5:"The songs that define unite and distinguish...",
//     //     title6:"The Sound of Hyder..",
//     //     subtitle6:"The songs that define unite and distinguish...",
//     // },
   
// ]
